In [1]:
import numpy as np

definicion

In [3]:
a=np.array([2,3,4,5])

In [ ]:
matriz = np.array([
    [1,2,3],
[4,5,6]])
print(matrix.shape) #dimensiones de la matriz se calcula el numero de filas y columnas
print(matrix.size) #numero de elementos de la matriz se calcula multiplicando el numero de filas por el numero de columnas
print(matrix.ndim) #numero de dimensiones de la matriz que indica 
print(matrix.dtype) #tipo de datos de los elementos de la matriz
print(matrix.itemsize) #tamaño en bytes de cada elemento de la matriz
print(matrix.nbytes) #tamaño en bytes de la matriz

(2, 3)
6
2
int64
8
48


In [ ]:
tres_dimensiones = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]])

print(tres_dimensiones.shape) #indica el numero de filas, columnas y capas
print(tres_dimensiones.size) #indica el numero de elementos de la matriz
print(tres_dimensiones.ndim) #indica el numero de dimensiones de la matriz



(3, 2, 3)
18
3


In [22]:
matrizZero = np.zeros((3,4)) #matriz de 3 filas y 4 columnas con valores 0
print(matrizZero)
matrizUnos = np.ones((2,3,5)) #matriz de 2 filas, 3 columnas y 4 capas con valores 1
print(matrizUnos)
matrizAleatorios = np.random.random((2,3)) #matriz de 2 filas y 3 columnas con valores aleatorios entre 0 y 1
print(matrizAleatorios)
matrizRango = np.arange(10) #matriz de 10 elementos con valores desde 0 hasta 9
print(matrizRango)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[9.05647143e-01 7.82368496e-01 1.63867870e-01]
 [5.98681471e-01 7.87322745e-04 3.31797536e-01]]
[0 1 2 3 4 5 6 7 8 9]


Operaciones

In [16]:
c1=np.array([1,2,3])
c2=np.array([4,5,6])

c1*c2


array([ 4, 10, 18])

In [17]:
data=np.array([10,20,30,40,50])
print(data.mean())
print(data.std())
print(data.var())
print(data.max())
print(data.min())
print(data.argmax())
print(data.argmin())

30.0
14.142135623730951
200.0
50
10
4
0


ingresar a los valores asociados