In [1]:
import numpy as np

Definicion

In [ ]:
una_dim=np.array([2,3,4,5])

In [14]:
dos_dimensiones = np.array([
    [1,2,3],
    [4,5,6]])
    
print(dos_dimensiones.shape) #dimensiones de la matriz se calcula el numero de filas y columnas
print(dos_dimensiones.size) #numero de elementos de la matriz se calcula multiplicando el numero de filas por el numero de columnas
print(dos_dimensiones.ndim) #numero de dimensiones de la matriz que indica 
print(dos_dimensiones.dtype) #tipo de datos de los elementos de la matriz
print(dos_dimensiones.itemsize) #tamaño en bytes de cada elemento de la matriz
print(dos_dimensiones.nbytes) #tamaño en bytes de la matriz

(2, 3)
6
2
int64
8
48


In [15]:
dos_dimensiones[1]

array([4, 5, 6])

In [16]:
dos_dimensiones[1][0]

np.int64(4)

In [ ]:
tres_dimensiones = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]])

print(tres_dimensiones.shape) #indica el numero de filas, columnas y capas
print(tres_dimensiones.size) #indica el numero de elementos de la matriz
print(tres_dimensiones.ndim) #indica el numero de dimensiones de la matriz

(3, 2, 3)
18
3


Otros tipos

In [6]:
matrizZero = np.zeros((3,4)) #matriz de 3 filas y 4 columnas con valores 0
print(matrizZero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
matrizUnos = np.ones((2,3,4)) #matriz de 2 filas, 3 columnas y 4 capas con valores 1
print(matrizUnos)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [41]:
matrizUnos[1][2][3]

np.float64(1.0)

In [12]:
matrizAleatorios = np.random.random((2,3)) #matriz de 2 filas y 3 columnas con valores aleatorios entre 0 y 1
print(matrizAleatorios)

[[0.62362856 0.45058272 0.25863432]
 [0.84876932 0.63032673 0.46152579]]


In [38]:
# Es un numero aleatorio entre 0 y 1
np.random.rand(3,3)

array([[0.00199879, 0.01342845, 0.41980694],
       [0.01708236, 0.97999785, 0.4398037 ],
       [0.34006132, 0.91755981, 0.11498497]])

In [39]:
# Es un numero aleatorio entre -1 y 1
np.random.randn(3,3)

array([[ 1.05292874,  0.11324408,  0.02689521],
       [-1.01336752, -0.37155262, -0.41976989],
       [ 0.286571  ,  0.48069582,  0.4448711 ]])

In [37]:
# Es un numero aleatorio entero entre 0 y 10 de 5 elementos
np.random.randint(0,10,5)

array([4, 4, 5, 2, 2])

In [34]:
# matriz de 2 filas y 3 columnas con valores aleatorios enteros entre 1 y 10
np.random.randint(1,10,(2,3)) 


array([[6, 1, 9],
       [8, 7, 1]])

In [11]:
# matriz de 10 elementos con valores desde 0 hasta 9
matrizRango = np.arange(10) 
print(matrizRango)

[0 1 2 3 4 5 6 7 8 9]


Operaciones

In [18]:
c1=np.array([1,2,3])
c2=np.array([4,5,6])


array([ 4, 10, 18])

In [21]:
# Para este caso las operaciones se realizan elemento a elemento

print(f"La suma de c1+c2 es: {c1+c2}")
print(f"La resta de c1-c2 es: {c1-c2}")
print(f"La multiplicacion de c1*c2 es: {c1*c2}")
print(f"La division de c1/c2 es: {c1/c2}")
print(f"La potencia de c1**c2 es: {c1**c2}")
print(f"El modulo de c1%c2 es: {c1%c2}")
print(f"El cociente de c1//c2 es: {c1//c2}")



La suma de c1+c2 es: [5 7 9]
La resta de c1-c2 es: [-3 -3 -3]
La multiplicacion de c1*c2 es: [ 4 10 18]
La division de c1/c2 es: [0.25 0.4  0.5 ]
La potencia de c1**c2 es: [  1  32 729]
El modulo de c1%c2 es: [1 2 3]
El cociente de c1//c2 es: [0 0 0]


In [23]:
c3=np.array([10,20,30,40,50])

print(c3.mean())
print(c3.std())
print(c3.var())
print(c3.max())
print(c3.min())
print(c3.argmax())
print(c3.argmin())c

30.0
14.142135623730951
200.0
50
10
4
0


In [40]:
c4=np.array([[10,20,30,40,50],
            [60,70,80,90,100]])

print(f"El valor maximo de data es: {c4.max()}")
print(f"El valor minimo de data es: {c4.min()}")
print(f"El valor del indice del maximo de data es: {c4.argmax()}")
print(f"El valor del indice del minimo de data es: {c4.argmin()}")
print(f"El valor de la media de data es: {c4.mean()}")
print(f"El valor de la desviacion estandar de data es: {c4.std()}")
print(f"El valor de la varianza de data es: {c4.var()}")



El valor maximo de data es: 100
El valor minimo de data es: 10
El valor del indice del maximo de data es: 9
El valor del indice del minimo de data es: 0
El valor de la media de data es: 55.0
El valor de la desviacion estandar de data es: 28.722813232690143
El valor de la varianza de data es: 825.0


Otras configuraciones

In [27]:
arr=np.array([1,2,3,4,5])

print(f"La matriz de 5 filas y 1 columna es: {arr.reshape(5,1)}")

print(f"La matriz de 1 fila y 5 columnas es: {arr.reshape(1,5)}")

La matriz de 5 filas y 1 columna es: [[1]
 [2]
 [3]
 [4]
 [5]]
La matriz de 1 fila y 5 columnas es: [[1 2 3 4 5]]
La matriz de 5 filas y 1 columna y 1 fila y 5 columnas es: [[1 2 3 4 5]]


In [31]:
arr=np.arange(9)

print(f"La matriz de 10 elementos es: {arr}")
print(f"La matriz de 10 elementos en 2 filas y 5 columnas es: {arr.reshape(3,3)}")

La matriz de 10 elementos es: [0 1 2 3 4 5 6 7 8]
La matriz de 10 elementos en 2 filas y 5 columnas es: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
print(f"La matriz de 10 elementos en 2 filas y 5 columnas es: {arr.reshape(2,5)}")
# Tener cuidado con el numero de elementos que se desea tener en la matriz ya que si no se cumple, se obtendra un error


ValueError: cannot reshape array of size 9 into shape (2,5)

In [33]:

arr=np.arange(10)

print(f"La matriz de 10 elementos es: {arr}")
print(f"La matriz de 10 elementos en 2 filas y 5 columnas es: {arr.reshape(2,5)}")

La matriz de 10 elementos es: [0 1 2 3 4 5 6 7 8 9]
La matriz de 10 elementos en 2 filas y 5 columnas es: [[0 1 2 3 4]
 [5 6 7 8 9]]
